# Generated by Django 3.0.2 on 2020-01-31 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, verbose_name='全国地方公共団体コード')),
                ('old_zipcode', models.CharField(max_length=5, verbose_name='（旧）郵便番号')),
                ('zipcode', models.CharField(max_length=7, verbose_name='郵便番号')),
                ('prefecture', models.CharField(max_length=128, verbose_name='都道府県')),
                ('city', models.CharField(max_length=128, verbose_name='市区町村名')),
                ('town_area', models.CharField(max_length=128, verbose_name='町域名')),
                ('prefecture_kana', models.CharField(max_length=128, verbose_name='都道府県カナ')),
                ('city_kana', models.CharField(max_length=128, verbose_name='市区町村名カナ')),
                ('town_area_kana', models.CharField(max_length=128, verbose_name='町域名カナ')),
            ],
        ),
    ]
